#!/bin/bash

echo -e "\n\nYou need to have added AWS credentials and exported AWS_PROFILE as per"
echo -e "\nthe normal AWS CLI requirements."

docker-machine create manager1
docker machine ssh manager1 "sudo docker swarm init"
docker-machine create worker1
JOIN=`docker-machine ssh manager1 "sudo docker swarm join-token worker" | head -3 | tail -1`
docker-machine ssh worker1 "sudo $JOIN"
