aws_region = "us-east-1"
ssh_private_key_file = "/root/terraform/id_rsa"
ssh_public_key_file = "/root/terraform/id_rsa.pub"
cluster_name = "mycluster"
worker_os = "centos"
ssh_username = "root"
ami = "ami-06e89768a2b7d7b8b"
