aws_region = "us-east-1"
ssh_private_key_file = "/root/terraform2/examples/terraform/aws/id_rsa"
ssh_public_key_file = "/root/terraform2/examples/terraform/aws/id_rsa.pub"
cluster_name = "mycluster"
worker_os = "centos"
ssh_username = "root"
ami = "ami-05e2b2c2c46eab874"
